Desktop/sapProject-master/sapApp/urls.py
from django.conf.urls import url
from .import views

app_name = 'sapApp'

urlpatterns= [
    url(r'^$', views.loggedIn, name='loggedIn'),
    url(r'^signIn/$', views.signIn, name='signIn'),
    url(r'^signingUp/$', views.signingUp, name='signingUp'),
    url(r'^exitSession/$', views.exitSession, name='exitSession'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^students/$', views.students, name='students'),
    url(r'^students2/(?P<sapID>[0-9]+)$', views.students2, name='students2'),
    url(r'^grades/$', views.grades, name='grades'),
    url(r'^grades2/$', views.grades2, name='grades2'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^specificreport/$', views.reports, name='specificreport'),
    url(r'^sortIt/$', views.sortIt, name='sortIt'),
    url(r'^userProfile/$', views.userProfile, name='userProfile'),
    url(r'^signUp/$', views.signUp, name='signUp'),
    url(r'^newStudent/$', views.newStudent, name='newStudent'),
]




Desktop/sapProject-master/sapProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sapApp/', include('sapApp.urls', namespace="sapApp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Desktop/sapProject-master/sapApp/models.py
from django.db import models

position_choices = {
    ('0', 'Boss'),
    ('1', 'Faculty'),
    ('2', 'IT'),
}

class user(models.Model):
    employee_id = models.IntegerField(default=0)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    work_position = models. CharField(max_length=16, choices=position_choices, default='0')
    user_password = models.CharField(max_length = 64)
    
    def __str__(self):
        return self.last_name

    
class student(models.Model):
    sap_id = models.IntegerField(default=0)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email_address = models.CharField(max_length = 64)
    group_number = models.IntegerField(default=1)
    territory = models.CharField(max_length=64)
    country = models.CharField(max_length=16)
    employee_id = models.IntegerField(default=0)
    training_program = models.CharField(max_length=128)
    
    def __str__(self):
        return self.last_name
    
class event(models.Model):
    event_id = models.IntegerField(default=0)
    event_name = models.CharField(max_length=256)
    event_date = models.DateField(auto_now=False)
    time_start = models.DateTimeField(auto_now=False)
    time_end = models.DateTimeField(auto_now=False)
    hex_id = models.IntegerField(default=0)
    event_comment = models.CharField(max_length = 256)
    employee_id = models.IntegerField(default=0)
    
    def __str__(self):
        return self.event_name
    
class grade(models.Model):
    sap_id = models.IntegerField(default=0)
    event_id = models.IntegerField(default=0)
    attendance = models.BooleanField()
    grade = models.IntegerField(default=0)
    
    def __str__(self):
        return self.sap_id
    
class activitie(models.Model):
    activity_id = models.IntegerField(default = 0)
    activity_name = models.CharField(max_length=64)
    employee_id = models.IntegerField(default = 0)
    group_number = models.IntegerField(default = 1)
    week_number = models.IntegerField(default =1)
    
    def __str__(self):
        return self.activity_name
    
class note(models.Model):
    title = models.CharField(max_length = 32)
    content = models.CharField(max_length = 256)
    note_date = models.DateField(auto_now = False)
    
    def __str__(self):
        return self.title
    
    

Desktop/sapProject-master/sapApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import user, student, event, grade, activitie, note
#from django.contrib.auth import logout
# Create your views here.

def dashboard(request):
    currentUser = get_object_or_404(user, employee_id=request.session["user"])
    context = {
        'currentUser': currentUser
    }
    return render(request, 'sapApp/dashboard.html', context)

def students(request):
    user_list = user.objects.all()
    student_list = student.objects.all().order_by('-sap_id').reverse()
    context = {
        'student_list': student_list,
        'user_list': user_list,
    }
    return render(request, 'sapApp/students.html', context)

def students2(request, sapID):
    currentStudent = get_object_or_404(student, sap_id=sapID)
    context = {
        'currentStudent': currentStudent
    }
    return render(request, 'sapApp/students2.html', context)

def sortIt(request):
    user_list = user.objects.all()
    if request.POST['sortby'] == '1':
        student_list = student.objects.all().order_by('-country').reverse()
    elif request.POST['sortby'] == '2':
        student_list = student.objects.all().order_by('-territory').reverse()
    elif request.POST['sortby'] == '3':
        student_list = student.objects.all().order_by('-last_name').reverse()
    elif request.POST['sortby'] == '4':
        student_list = student.objects.all().order_by('-group_number').reverse()
    else:
        student_list = student.objects.all().order_by('-sap_id').reverse()
    context = {
        'student_list': student_list,
        'user_list': user_list,
    }
    return render(request, 'sapApp/students.html', context)

def grades(request):
    return render(request, 'sapApp/grades.html')

def grades2(request):
    return render(request, 'sapApp/grades2.html')

def reports(request):
    return render(request, 'sapApp/reports.html')

def specificreport(request):
    return render(request, 'sapApp/specificreport.html')

def userProfile(request):
    currentUser = get_object_or_404(user, employee_id=request.session["user"])
    context = {
        'currentUser': currentUser
    }
    return render(request, 'sapApp/userprofile.html', context)

def loggedIn(request):
    if request.session["user"] > 0:
        currentUser = get_object_or_404(user, employee_id=request.session["user"])
        context = {
            'currentUser': currentUser
        }
        return render(request, 'sapApp/dashboard.html', context)
    if request.session["user"] == -1:
        return render(request, 'sapApp/login.html')

def signIn(request):
    userList = user.objects.all()
    for userTry in userList:
        if userTry.employee_id == int(request.POST['userName']):
            if userTry.user_password == request.POST['userPassword']:
                request.session["user"] = userTry.employee_id
    if request.session["user"] >= 0:
        currentUser = get_object_or_404(user, employee_id=request.session["user"])
        context = {
            'currentUser': currentUser
        }
        return render(request, 'sapApp/dashboard.html', context)
    else:
        request.session["user"] = -1
        return render(request, 'sapApp/login.html')

def newStudent(request):
    addingStudent = student(sap_id = int(request.POST['newSAP']), first_name = request.POST['newFirst'], last_name = request.POST['newLast'], email_address = request.POST['newEmail'], group_number = int(request.POST['newGroup']), territory = request.POST['newTerritory'], country = request.POST['newCountry'], employee_id = int(request.POST['newManager']), training_program = request.POST['newTraining'])
    addingStudent.save()
    user_list = user.objects.all()
    student_list = student.objects.all().order_by('-sap_id').reverse()
    context = {
        'student_list': student_list,
        'user_list': user_list,
    }
    return render(request, 'sapApp/students.html', context)

def signingUp(request):
    addingUser = user(employee_id = request.POST['employee_num'], first_name = request.POST['first_name'], last_name = request.POST['last_name'], work_position = request.POST['work_position'], user_password = request.POST['password1'])
    addingUser.save()
    return render(request, 'sapApp/Signup.html')

def signUp(request):
    return render(request, 'sapApp/Signup.html')

def exitSession(request):
    request.session['user'] = -1
    return render(request, 'sapApp/login.html')

Desktop/sapProject-master/sapApp/templates/sapApp/Signup.html
<html>
    <head>
        {% load static %}
        <title>Sign Up</title>
		<link rel="stylesheet" type="text/css" href="{% static 'sapApp/signup.css' %}">
    </head>
    <body>
	 <div class="webpage">
            <div class="header">
                <div class = "left">
                    
                        <div class="bar-photo">
                            <a href="/sapApp/dashboard/"><img src = "{% static 'sapApp/Images/saplogo.png' %}" width=65 height=32></a>
                        </div>
                        <div class="bar-item-container">
                            <div class="bar-item">
                                <a href="/sapApp/students/"><span class="item">STUDENTS</span></a>
                            </div>
                            </div>
                        
                    <div class="dropdown2">
                                <span class="item" style="margin-left: 1.8em; cursor: pointer;">GRADES</span>
                            <div class="dropdown-content2">
                        <ul>
                            <a href="/sapApp/grades/"><li>Asia Pacific Japan</li></a>
                            <a href="/sapApp/grades/"><li>Europe Middle East</li></a>
                            <a href="/sapApp/grades/"><li>Moscow East Europe</li></a>
                            <a href="/sapApp/grades/"><li>North America</li></a>
                        </ul>
                    </div>
                        </div>
                    
                    
                        <div class="bar-item-container">
                            <div class="bar-item">
                                <a href="/sapApp/reports/"><span class="item">REPORTS</span></a>
                            </div>
                        
                    </div>
                </div>
                <div class = "right">
                    <div class="bar-item2">
                            <span class="greetings">Hi, Lyn Reyes!</span>
                        </div>
                        <div class="dropdown">
                            <img src = "{% static 'sapApp/Images/usericon.png' %}" width=32 height=28>
                            <div class="dropdown-content">
                        <ul>
                            <a href="/sapApp/userProfile"><li>My Profile</li></a>
                            <a href="/sapApp/signUp/"><li>Create an Account</li></a>
                            <a href="/sapApp/login/"><li>Log-out</li></a>
                        </ul>
                    </div>
                        </div>
                </div>
            </div>
            <div class="header2">
                <div class="header2-bar2">
                    <div class="item-container2">
                    <div class="bar-title">
                        <span class ="bigtext">Sign Up</span>
                    </div>

                    </div>
                </div>
            </div>
            <div class="middle">
                 <form action="{% url 'sapApp:signingUp' %}" method="post">
                {% csrf_token %}
                <div class="table-container">
                    <div class="head2">First Name</div><input type="text" name="first_name" id="first_name"  class="input2">
                    <div class="head3">Last Name</div><input type="text" name="last_name" id="last_name" class="input2">
                    <div class="head3">Position</div><input type="text" name="work_position" id="work_position" class="input2">
                    <div class="head3">Employee #</div><input type="text" name="employee_num" id="employee_num" class="input2">
                    <div class="head3">Password</div><input type="text" name="password1" id="password1" class="input2">
                    <div class="head3">Confirm Pass.</div><input type="text" name="password2" id="password2" class="input2"><br>
                    <button type="submit" class="button1"> Submit</button>
                </div>
                </form>             
            </div>
        </div>
    </body>
</html>

Desktop/sapProject-master/sapApp/templates/sapApp/dashboard.html
<html>
    <head>
        {% load static %}
        <title>My Dashboard</title>
		<link rel="stylesheet" type="text/css" href="{% static 'sapApp/dashboard.css' %}">
    </head>
    <body onload="off()">
		<div id="overlay">
			<div class="item-container4">
				<div id="note"> Add a Note </div>
				<div id="close" onclick="off()"> X </div>
				<div id="item-container5">
					<div id="title"> <input type="text" placeholder="Title" id="note_title"> </div>
					<div id="content">
						<textarea id="note_content" rows="4" cols="50"> </textarea>
					</div>
				</div>
				<button id="addnote"> Add a Note </button>
			</div>
		</div>
		
		<div id="event_overlay">
			<div class="item-container4">
				<div id="note"> Add a Calendar Event </div>
				<div id="close" onclick="off()"> X </div>
				<div id="item-container6">
					<div id="name"> Event Name: <input type="text" id="event_title"> </div>
					<div id="date"> Date: <input type="date" id="event_date"> </div>
					<div id="time"> Time: <input type="time" id="event_time"> </div>
					<div id="color"> Color: <input type="color" id="event_color"> </div>
					<div id="content"> Notes:
						<textarea id="event_notes" rows="2" cols="8"> </textarea>
					</div>
				</div>
				<button id="addevent"> Add an Event </button>
			</div>
		</div>
		
		
		<div id="todo_overlay">
			<div class="item-container7">
				<div id="note"> Add To Do </div>
				<div id="close" onclick="off()"> X </div>
				<div id="item-container8">
					<div id="todo_name"> Task: <input type="text" id="todo_title"> </div>
					<div id="todo_time"> Time Due: <input type="time" id="todo_time"> </div>
				</div>
				<button id="addtodo"> Add Task </button>
			</div>
		</div>
		
		<div id="fullnote_overlay">
			<div class="item-container4">
				<div id="note"> Title of the note </div>
				<div id="close" onclick="off()"> X </div>
				<div id="item-container6">
					<div id="full_content"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </div>
				</div>
			</div>
		</div>
		
		 <div id="upload_overlay">
			<div class="item-container7">
				<div id="note"> Upload A File </div>
				<div id="close" onclick="off()"> X </div>
				<div id="item-container6">
                    <form action="/action_page.php">
                            <input type="file" name="pic">
                            <button id="uploadF"> Upload </button>  
                    </form>
				</div>
			</div>
        </div>
		
        <div class="webpage">
            <div class="header">
                <div class = "left">
                    
                        <div class="bar-photo">
                            <a href="/sapApp/dashboard/"><img src = "{% static 'sapApp/Images/saplogo.png' %}" width=65 height=32></a>
                        </div>
                        <div class="bar-item-container">
                            <div class="bar-item">
                                <a href="/sapApp/students/"><span class="item">STUDENTS</span></a>
                            </div>
                            </div>
                        
                    <div class="dropdown2">
                                <span class="item" style="margin-left: 1.8em; cursor: pointer;">GRADES</span>
                            <div class="dropdown-content2">
                        <ul>
                            <a href="/sapApp/grades/"><li>Asia Pacific Japan</li></a>
                            <a href="/sapApp/grades/"><li>Europe Middle East</li></a>
                            <a href="/sapApp/grades/"><li>Moscow East Europe</li></a>
                            <a href="/sapApp/grades/"><li>North America</li></a>
                        </ul>
                    </div>
                        </div>
                    
                    
                        <div class="bar-item-container">
                            <div class="bar-item">
                                <a href="/sapApp/reports/"><span class="item">REPORTS</span></a>
                            </div>
                        
                    </div>
                </div>
                <div class = "right">
                    <div class="bar-item2">
                            <span class="greetings">Hi, {{ currentUser.first_name }} {{ currentUser.last_name }}!</span>
                        </div>
                        <div class="dropdown">
                            <img src = "{% static 'sapApp/Images/usericon.png' %}" width=32 height=28>
                            <div class="dropdown-content">
                        <ul>
                            <a href="/sapApp/userProfile/"><li>My Profile</li></a>
                            <a href="/sapApp/signUp/"><li>Create an Account</li></a>
                            <a href="/sapApp/exitSession/"><li>Log-out</li></a>
                        </ul>
                    </div>
                        </div>
                </div>
            </div>
            <div class="header2">
                <div class="header2-bar2">
                    <div class="item-container2">
                    <div class="bar-title">
                        <span class ="bigtext">MY DASHBOARD</span>
						<span class="smalltext" onclick="uploadFile()"> Upload a File </span>
						<span class="smalltext" onclick="addEvent()"> Add Calendar Event </span>
						<span class="smalltext" onclick="addNote()"> Add Notes </span>
						<span class="smalltext" onclick="addtoDo()"> Add To Do </span>
                    </div>
                    <div class="search-container">
                        <input type="text" class="search" placeholder="Search">
                    </div>
                    </div>
                </div>
            </div>
            <div class="middle">
                <div class="post-container">
                    <div class="post" onclick="expandNote()">
                        <div class="top-color">.</div>
                        <span class="title">Meeting Notes</span>
                        <span class="body">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>
                        <span class="time">Date Modified: Oct. 10, 2017 </span>
                    </div>
                    <div class="post" onclick="expandNote()">
                        <div class="top-color">.</div>
                        <span class="title">Meeting Notes</span>
                        <span class="body">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>
                        <span class="time">Date Modified: Oct. 10, 2017 </span>
                    </div>
                    <div class="post" onclick="expandNote()">
                        <div class="top-color">.</div>
                        <span class="title">Faculty Assessment</span>
                        <span class="body">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
                        <span class="time">Date Modified: Oct. 10, 2017 </span>
                    </div>
                </div>
                <div class="side-container">
                <div class="top-color2">.</div>
                <div class="calendar">
                    <span class="calendar-title">Calendar</span>
                    <img src="{% static 'sapApp/Images/calendar.jpg' %}" width=400 style="margin-left: 1.7em; margin-top: 1em;">
                    <div class="todo">
                        <span class="todo-title">To-do List</span>
                        
                        <span class="todo-row"><input type="checkbox">Meeting at 9am</span>
                        <span class="todo-row"><input type="checkbox">Grades due at 12nn</span>
                        <span class="todo-row"><input type="checkbox">Meeting at 3pm</span>
                        <span class="todo-row"><input type="checkbox">Meeting at 4pm</span>
                    </div>
                </div>
            </div>
            </div>
            
        </div>
		
		<script>
			function addNote(){
				document.getElementById("overlay").style.display = "block";
			}
			function addEvent(){
				document.getElementById("event_overlay").style.display = "block";
			}
			function addtoDo(){
				document.getElementById("todo_overlay").style.display ="block";
			}
			function expandNote(){
				document.getElementById("fullnote_overlay").style.display = "block";
			}
			function uploadFile(){
				document.getElementById("upload_overlay").style.display = "block";
			}
			function off(){
				document.getElementById("overlay").style.display = "none";
				document.getElementById("event_overlay").style.display = "none";
				document.getElementById("todo_overlay").style.display = "none";
				document.getElementById("fullnote_overlay").style.display = "none";
				document.getElementById("upload_overlay").style.display = "none";
			
			}
		</script>
    </body>
</html>

Desktop/sapProject-master/sapApp/templates/sapApp/login.html


<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title> Log in</title>
	<link rel="stylesheet" type="text/css" href="{% static 'sapApp/login.css' %}">
</head>


<body>

	<div id=maincontainer>
	
		<div id=logocontainer>
			<img src="{% static 'sapApp/Images/SAPlogin.png' %}" height="70" width="400" background-color="white">
		</div>

		<div id="logincontainer"> 
            <form action="{% url 'sapApp:signIn' %}" method = "post">
                {% csrf_token %}
			<div class="blueblock">
				<p align="center"><br>Academy Evaluation Portal</p>
			</div>

			<div id="userpass"> 
				<br><br>
				<span class="fontUP">&emsp;EMPLOYEE ID:</span>
				<br>
				<input type="text" class="username" name="userName">
				<br><br>
				<span class="fontUP">&emsp;PASSWORD:</span>
				<br>
				<input type="text" class="password" name="userPassword">
				<br>

			</div>

			<button type="submit">Log In</button>
            </form>
		</div>


	</div>


</body>
</html>



Desktop/sapProject-master/sapApp/templates/sapApp/students.html
<html>
    <head>
        {% load static %}
        <title>List of Students</title>
		<link rel="stylesheet" type="text/css" href="{% static 'sapApp/students.css' %}">
    </head>
    <body>	
	
        <div class="webpage">
            <div class="header">
                <div class="header-bar1">
                    <div class="item-container">
                        <div class="bar-photo">
                            <a href="/sapApp/dashboard/"><img src = "{% static 'sapApp/Images/saplogo.png' %}" width=65 height=32></a>
                        </div>
                        <div class="bar-item-container">
                        <div class="bar-item">
                            <a href="/sapApp/students/"><span class="item">STUDENTS</span></a>
                        </div>
                            </div>
                        <div class="bar-item-container">
                        <div class="bar-item">
                            <a href="/sapApp/grades/"><span class="item">GRADES</span></a>
                        </div>
                        </div>
                        <div class="bar-item-container">
                        <div class="bar-item">
                            <a href="/sapApp/reports/"><span class="item">REPORTS</span></a>
                        </div>
                    </div>
                        
                    </div>
                    <div class="item-container3">
                        <div class="bar-item2">
                            <span class="greetings">Hi, Lyn Reyes!</span>
                        </div>
                        <div class="bar-photo">
                            <img src = "{% static 'sapApp/Images/usericon.png' %}" width=32 height=28>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header2">
                <div class="header2-bar2">
                    <div class="item-container2">
                    <div class="bar-title">
                        <span class ="bigtext">MY STUDENTS</span>
                    </div>
                    <div class="search-container">
                        <input type="text" class="search" placeholder="Search">
                    </div>
                    </div>
                </div>
            </div>

            
            <div class="middle">
                <div id="sortcontainer">
					<button id="addStudent" onclick="addStudent()"> Add Students </button>
					<form action="{% url 'sapApp:sortIt' %}" method = "post">
                        {% csrf_token %}
						<select name="sortby" class="textbox2">
							<option value="1"> View by Country </option>    
							<option value="2"> View by Territory </option>
							<option value="3"> View by Last Name </option>
							<option value="4"> View by Group </option> 
						</select>
						<button type="submit" class="item">REFRESH</button>
                    </form>
                </div>
                <div style="overflow-y:auto;">
                <div class="table-container">
                    <div class="top-color">.</div>
                    <div class="innercontainer">
                    <table>
                        <tr>

                            <th><div class="bigger">Name</div></th>
                            <th><div class="bigger">Group Number</div></th>
                            <th><div class="bigger">Territory</div></th>
                            <th><div class="bigger">Country</div></th>
                        </tr>
						{% for student in student_list %}
                        <tr>
                            <td><a href="{% url 'sapApp:students2' student.sap_id %}">{{student.last_name}}, {{student.first_name}}</a></td>
                            <td>{{student.group_number}}</td>
                            <td>{{student.territory}}</td>
                            <td>{{student.country}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    </div>
                </div>
                </div>
                
            </div>
        </div>
        
        <div id="student_overlay">
			<div class="item-container4">
				<div id="note"> Add a Student </div>
				<div id="close" onclick="off()"> X </div>
                <form action="{% url 'sapApp:newStudent' %}" method = "post">
                {% csrf_token %}
				<div id="item-container6">
                    <div id="lastname"> Last Name: <input type="text" class="info" name="newLast"> </div> 
                    <div id="firstname"> First Name: <input type="text" class="info" name="newFirst"> </div>
                    <div id="sapid"> SAP ID #: <input type="text" class="info" name="newSAP"> </div>
                    <div id="email"> Email: <input type="email" class="info" name="newEmail"> </div>
                    <div id="group"> Group Number: <input type="text" class="info" name="newGroup"> </div>
                    <div id="territory"> Territory: <input type="text" class="info" name="newTerritory"> </div>
                    <div id="country"> Country: <input type="text" class="info" name="newCountry"> </div>
                    <div id="training"> Training Program: <input type="text" class="info" name="newTraining"> </div>
                    <div id="manager"> Manager: <input type="text" class="info" name="newManager"> </div>
				</div>
                    <button id="addStud" type="submit"> Add Student </button>
                </form>
             </div>
        </div>

        
        <script>
            function addStudent(){
				document.getElementById("student_overlay").style.display = "block";
            }
			function off(){
				document.getElementById("student_overlay").style.display = "none";
			}
        </script>
		
    </body>
</html>